import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/Navbar";
import Menu from "@/components/menu/page";
import { ReactNode } from "react";
import styles from "./layout.module.css";
import { MSWComponent } from "@/app/_component/MSWComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const bebas_neue = Bebas_Neue({
  subsets: ["latin"],
  weight: ["400"],
});

type Props = { children: ReactNode; modal: ReactNode };

export default function RootLayout({ children, modal }: Props) {
  return (
    <html lang="en" className={bebas_neue.className}>
      <body className={styles.body}>
        <div className={styles.container}>
          <MSWComponent />
          <Menu />
          <NavBar />
          <div className={styles.content}>
            {children}
            {modal}
          </div>
        </div>
      </body>
    </html>
  );
}
